apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: vm-pool-windows
spec:
  replicas: 0
  virtualMachineTemplate:
    spec:
      runStrategy: RerunOnFailure
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: rootdisk-dv
          spec:
            source:
              pvc:
                name: windows-base-v20230409
                namespace: koray
            storage:
              resources:
                requests:
                  storage: 32Gi
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: vm-pool-windows
        spec:
          livenessProbe:
            initialDelaySeconds: 240
            periodSeconds: 5
            httpGet:
              port: 8080
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
            successThreshold: 1
          domain:
            cpu:
              cores: 1
          resources:
              requests:
                memory: 4Gi
